# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6

    steps:
      - checkout

      - restore_cache:
          keys:
          - cache-{{ checksum "requirements/prod.txt" }}-{{ checksum "requirements/dev.txt" }}

      - run:
          name: Install Git LFS
          command: |
            curl -s https://packagecloud.io/install/repositories/github/git-lfs/script.deb.sh | sudo bash
            sudo apt-get install git-lfs
            git lfs install

      - run:
          name: Pull LFS Files
          command: git lfs pull

      - run:
          name: Install Shellcheck
          command: |
            curl -OL https://github.com/koalaman/shellcheck/releases/download/stable/shellcheck-stable.linux.x86_64.tar.xz
            tar xf shellcheck-stable.linux.x86_64.tar.xz
            sudo mv shellcheck-stable/shellcheck /usr/local/bin
          working_directory: /tmp/shellcheck

      - run:
          name: install dependencies
          command: |
            pip install --quiet -r requirements/prod.txt -r requirements/dev.txt

      - save_cache:
          key: cache-{{ checksum "requirements/prod.txt" }}-{{ checksum "requirements/dev.txt" }}
          paths:
            - ~/.local

      - run:
          name: run linting
          when: always
          command: |
            cd lab8 || true; PYTHONPATH=. ./tasks/lint.sh

      - run:
          name: run prediction tests
          when: always
          command: |
            cd lab8 || true; PYTHONPATH=. ./tasks/test.sh

      - store_artifacts:
          path: test-reports
          destination: test-reports
